### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by duanedsouza**

### CODE REVIEW

**Comment by sinherle** [comment]
Can one of the admins verify this patch?

**Comment by sinherle** [comment]
Can one of the admins verify this patch?

**Comment by bhavenamrata** [comment]
ok to test

**Comment by sinherle** [comment]
Build finished.

**Comment by sinherle** [comment]
Build finished.

**Comment by duanedsouza** [comment]
ok to test

**Comment by bhavenamrata** [comment]
test this please

**Comment by sinherle** [comment]
Build finished.

**Comment by sinherle** [comment]
Build finished.

**Pull request closed without merging**
